import CoreLocation
import Foundation

/// Which of the nine Bay Area counties contains a coordinate.
///
/// WHY THIS REPLACED "NEAREST COUNTY CENTRE": the previous implementation
/// resolved a GPS fix by measuring the distance to nine hardcoded county
/// centroids and taking the closest. Measured against the real boundaries that
/// is wrong for 10 of 27 actual Bay Area cities:
///
///   Oakland   → said San Francisco      Daly City → said San Francisco
///   Berkeley  → said San Francisco      Palo Alto → said San Mateo
///   Fremont   → said Santa Clara        Hayward   → said Contra Costa
///
/// Someone standing in Oakland was shown San Francisco's programs. A centroid
/// cannot describe a county: Alameda's centre is out past Livermore, so most of
/// Alameda's population is closer to San Francisco's centre than to its own.
///
/// The boundaries are generated by scripts/generate/generate-county-lookup.cjs,
/// simplified to ~111 m and 35 KB, with a build-time assertion that 27 real
/// cities still classify correctly.
public struct BayAreaCounties: Sendable {
    public struct County: Codable, Sendable, Equatable {
        public let name: String
        public let slug: String
        /// [polygon][ring][point][lng, lat] — GeoJSON order, longitude first.
        public let polygons: [[[[Double]]]]
    }

    private struct Payload: Codable {
        let counties: [County]
    }

    public let counties: [County]

    public init(counties: [County]) {
        self.counties = counties
    }

    /// Load the lookup bundled with the package.
    public static func bundled() throws -> BayAreaCounties {
        guard let url = Bundle.module.url(forResource: "county-lookup", withExtension: "json") else {
            throw CocoaError(.fileNoSuchFile)
        }
        return try load(contentsOf: url)
    }

    public static func load(contentsOf url: URL) throws -> BayAreaCounties {
        let payload = try JSONDecoder().decode(Payload.self, from: Data(contentsOf: url))
        return BayAreaCounties(counties: payload.counties)
    }

    /// Ray casting. Mirrors the JS and Dart ports — keep the three in step.
    private static func inRing(_ x: Double, _ y: Double, _ ring: [[Double]]) -> Bool {
        guard ring.count > 2 else { return false }
        var inside = false
        var j = ring.count - 1
        for i in 0..<ring.count {
            let xi = ring[i][0], yi = ring[i][1]
            let xj = ring[j][0], yj = ring[j][1]
            if (yi > y) != (yj > y), x < (xj - xi) * (y - yi) / (yj - yi) + xi {
                inside.toggle()
            }
            j = i
        }
        return inside
    }

    /// The county containing this coordinate, or nil if it is outside all nine.
    ///
    /// Returning nil matters: someone in Sacramento should be told this covers
    /// the Bay Area, not quietly handed Solano's programs.
    public func county(at coordinate: CLLocationCoordinate2D) -> County? {
        let x = coordinate.longitude
        let y = coordinate.latitude
        for county in counties {
            for polygon in county.polygons {
                guard let outer = polygon.first, Self.inRing(x, y, outer) else { continue }
                var inHole = false
                for hole in polygon.dropFirst() where Self.inRing(x, y, hole) {
                    inHole = true
                    break
                }
                if !inHole { return county }
            }
        }
        return nil
    }

    /// Display label matching the rest of the app ("San Francisco", not
    /// "San Francisco County" — it is a consolidated city-county).
    public static func displayName(for county: County) -> String {
        county.name == "San Francisco" ? "San Francisco" : "\(county.name) County"
    }
}
