services:
  meilisearch:
    image: getmeili/meilisearch:v1.38.2
    container_name: bay-navigator-meilisearch
    restart: unless-stopped
    ports:
      - '7700:7700'
    environment:
      MEILI_MASTER_KEY: '${MEILI_MASTER_KEY}'
      MEILI_ENV: production
    volumes:
      - ./data:/meili_data
