name = "baynavigator-ai-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "c19818aa9be140eeb372bb45da855919"

[vars]
AI_ORIGIN = "https://ai.baytides.org"
OLLAMA_ORIGIN = "https://ollama.baytides.org"
MAIN_ORIGIN = "https://baynavigator.org"
